# Site settings
title: 知其变，守其恒，为天下式
email: ice1000@foxmail.com
author: Tesla Ice Zhang >>= Akirina Wu
description: >
  ice1000's blog
baseurl: ""
url: "http:/ice1000.org/"
keywords: ice1000, Akirina, blog
favicon: /favicon.ico
twitter: ice1000kotlin
github_username: ice1000
permalink: /:year/:month/:day/:title/
domain: ice1000.org
# Build settings
markdown: kramdown
highlighter: rouge
paginate: 12
repository: https://github.com/ice1000/ice1000.github.io
repository_name: ice1000.github.io